---
- name: Test Windows Connection
  hosts: all
  connection: winrm
  gather_facts: false

  tasks:
    - name: Run whoami on Windows host
      ansible.windows.win_command: whoami
      register: whoami_output

    - name: Show whoami output
      debug:
        var: whoami_output.stdout
